<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lrcore</groupId>
        <artifactId>lrcore-system-modules</artifactId>
        <version>v1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>lrcore-flowable</artifactId>
    <name>flowable工作流引擎</name>
    <description>
        lrcore-flowable工作流引擎
    </description>

    <dependencies>
        <!-- web场景开发核心模块 -->
        <dependency>
            <groupId>com.lrcore</groupId>
            <artifactId>lrcore-common-web</artifactId>
        </dependency>

        <!-- 工作流引擎-->
        <dependency>
            <groupId>com.lrcore</groupId>
            <artifactId>lrcore-common-flowable</artifactId>
        </dependency>

        <!-- 引入工作流api-->
        <dependency>
            <groupId>com.lrcore</groupId>
            <artifactId>lrcore-flowable-api</artifactId>
            <version>v1.0.0</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>${service-name-system}-${nacos.active}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
