<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lrcore</groupId>
        <artifactId>lrcore-bizrule-modules</artifactId>
        <version>v1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>lrcore-bizrule</artifactId>
    <name>bizrule业务实现</name>
    <description>
        lrcore-bizrule规则模块
    </description>

    <dependencies>
        <!-- web场景开发核心模块 -->
        <dependency>
            <groupId>com.lrcore</groupId>
            <artifactId>lrcore-common-web</artifactId>
        </dependency>
        <!-- 本地缓存 Source: https://mvnrepository.com/artifact/com.github.ben-manes.caffeine/caffeine -->
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>3.2.4</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${service-name-rule}-${nacos.active}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
