<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.lrcore</groupId>
        <artifactId>lrcore-system-modules</artifactId>
        <version>v1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>lrcore-system-api</artifactId>
    <name>system-api系统对外接口</name>
    <description>
        system-api系统对外接口
    </description>

    <dependencies>
        <!-- Common Core-->
        <dependency>
            <groupId>com.lrcore</groupId>
            <artifactId>lrcore-common-core</artifactId>
        </dependency>
    </dependencies>
</project>
